#server:
#  port: 8989
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        hibernate:
#        "[format_sql]": true
#        "[user_sql_comments]": true
#        "[highlight_sql]": true
#        "[hbm2ddl.auto]": update
#    open-in-view: true
#    show-sql: true
